[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-Wl,-dynamic-linker,/lib/ld-linux-aarch64.so.1"]
