name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        run: |
          sudo apt-get install -y pkg-config curl gcc clang libudev-dev unzip xz-utils \
            git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build \
            ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: Install ldproxy
        run: |
          cargo install ldproxy
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Run build
        run: cargo build --release

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check
